// import { useState, useEffect } from 'react';
// import moment from 'moment';
import cn from 'classnames';
import Head from 'next/head'
// import Image from 'next/image'

import Products from '../components/Products';
import Breadcrumb from '../components/Breadcrumb';
import Header from '../components/Header';
import styles from '../styles/Home.module.css'

import '../node_modules/react-datepicker/dist/react-datepicker.css';
import 'bootstrap/dist/css/bootstrap.min.css';

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Lovevery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"></link>
      </Head>
      <Header />
      <main className={cn(styles.main)}>
        <div className={cn(styles.productContainer, 'w-75')}>
          <Breadcrumb />
          <Products/>
        </div>
      </main>
    </div>
  )
}

